In [5]:
import pandas as pd
from sqlalchemy import create_engine

In [51]:
import os
os.environ['DB_PASSWORD'] = ''

In [52]:
# 1. สร้างท่อเชื่อมต่อวิ่งไปหา MySQL (กรอกรหัสผ่านและชื่อ db เหมือนใน DBeaver)
#engine = create_engine("mysql+pymysql://root:P09062005p@localhost:3306/Shoppee_db")
engine = create_engine(f"mysql+pymysql://root:{os.environ.get('DB_PASSWORD')}@localhost:3306/Shoppee_db")

#ดึงข้อมูล Orders 
df_orders = pd.read_sql("SELECT * FROM shopee_orders_thailand", engine)

# ดึงข้อมูล Order Items
df_items = pd.read_sql("SELECT * FROM shopee_order_items_thailand", engine)

#ดึงข้อมูล Products 
df_products = pd.read_sql("SELECT * FROM shopee_products_thailand", engine)

#ดึงข้อมูล Campaigns
df_campaigns = pd.read_sql("SELECT * FROM shopee_campaigns_thailand", engine)

In [43]:
print("Orders:", df_orders.shape)
print("Items:", df_items.shape)
print("Products:", df_products.shape)
print("Campaigns:", df_campaigns.shape)

Orders: (300000, 12)
Items: (480481, 16)
Products: (4880, 8)
Campaigns: (20, 5)

ทำ 1: Cohort Analysis (ผลกระทบแคมเปญต่อการซื้อซ้ำ): วิเคราะห์ว่า ลูกค้าที่หลงเข้ามาซื้อของกับเราครั้งแรกเพราะ "โปรโมชั่นเด็ด 11.11" มีอัตราการกลับมาซื้อซ้ำ (Retention Rate) ในเดือนต่อๆ ไป มากหรือน้อยกว่า ลูกค้าที่เดินเข้ามาซื้อเองใน "วันธรรมดา"? (วัดคุณภาพของลูกค้าที่ได้มาจากโปรโมชั่น)

In [72]:
import pandas as pd
import numpy as np

df_orders['order_date'] = pd.to_datetime(df_orders['order_date']) # Convert text in to datetime data
df_orders['order_month'] = df_orders['order_date'].dt.to_period('M') # it cut day and just have Month and Year

df_merged = pd.merge(df_orders, 
                    df_campaigns[['campaign_id', 'campaign_name']], 
                    on='campaign_id', 
                    how='left')  # this part is like a left join in SQL to find not match campaign_id is Null day 
df_merged['campaign_name'] = df_merged['campaign_name'].fillna('Normal Day') # and we use null day to fillna be normal day


# find First purchased month for each 
df_merged['first_order_month'] = df_merged.groupby('customer_id')['order_month'].transform('min')   

# first interacted with us (their birthday month).
#ส่วนที่ 1: คำนวณความต่างของ "ปี" แล้วแปลงให้เป็นเดือน
df_merged['cohort_index'] = (df_merged['order_month'].dt.year - df_merged['first_order_month'].dt.year) * 12 + \
                            (df_merged['order_month'].dt.month - df_merged['first_order_month'].dt.month)#ส่วนที่ 2: คำนวณความต่างของ "เดือน" ในปีนั้นๆ

cohort_data = df_merged.groupby(['campaign_name', 'cohort_index'])['customer_id'].nunique().reset_index()

cohort_pivot = cohort_data.pivot(index='campaign_name',columns='cohort_index',values = 'customer_id')
cohort_size = cohort_pivot.iloc[:,0] #Start the first column is a column 0
retention_matrix = cohort_pivot.divide(cohort_size,axis=0) * 100

retention_rate = retention_matrix[[0,1,2,3]].round(1)
retention_rate

cohort_index       0     1     2     3
campaign_name
10.10 Sale     100.0  38.4  22.2  20.8
11.11 Sale     100.0  31.1  30.9  23.7
12.12 Sale     100.0  34.9  33.7  32.1
9.9 Sale       100.0  27.5  16.1  20.6
Normal Day     100.0  22.2  20.8  19.5
Songkran Sale  100.0  10.3   7.7   9.0

In [105]:
retention_rate.to_csv('retention_rate.csv')
print("✅ Saved!")

✅ Saved!

ทำ 2: Price Elasticity of Demand during Campaigns: คำนวณหาความยืดหยุ่นของราคาในช่วงแคมเปญเทียบกับวันปกติ เพื่อตอบคำถามว่า "สินค้าหมวดไหนที่ลูกค้าเซนซิทีฟกับราคามากๆ ช่วงลดราคาปุ๊บ ยอดสั่งซื้อพุ่งขึ้นเป็น 10 เท่าตัวทันที"

In [64]:
# เชื่อมตารางสินค้า (items) เข้ากับหมวดหมู่สินค้า (products) โดยใช้ product_id เป็นตัวเชื่อม
df_item_products = pd.merge(df_items,
                            df_products[['product_id','category']],
                            on='product_id',
                            how='left')

# เชื่อมตารางที่ได้จากขั้นตอนแรกเข้ากับออเดอร์ (orders) เพื่อระบุ campaign_id ของแต่ละการสั่งซื้อ
df_full = pd.merge(df_item_products,
                   df_orders[['order_id','campaign_id']],
                   on = 'order_id',
                   how='left')

# เชื่อมเข้ากับตารางแคมเปญเพื่อนำชื่อแคมเปญ (campaign_name) มาใช้
df_full = pd.merge(df_full,
                   df_campaigns[['campaign_id','campaign_name']],
                   on = 'campaign_id',
                   how= 'left')

df_full['period'] = df_full['campaign_name'].apply(
    lambda x: 'Campaign' if pd.notna(x) else 'Normal Day'
)

df_completed = df_full[df_full['item_status'] == 'Completed']

elasticity = df_completed.groupby(['category', 'period']).agg(
    avg_price = ('unit_price_after_discount','mean'),
    avg_discount_pct = ('discount_percent','mean'),
    avg_quantity = ('quantity','mean')
).round(2).reset_index()

elasticity_pivot = elasticity.pivot(index='category',
                                    columns = 'period',
                                    values=['avg_price', 'avg_discount_pct','avg_quantity'])

elasticity_pivot.columns = ['_'.join(col).strip() for col in elasticity_pivot.columns]
elasticity_pivot = elasticity_pivot.reset_index()

# คำนวณเปอร์เซ็นต์การเปลี่ยนแปลงของยอดขาย (Demand Change %) 
elasticity_pivot['demand_change_pct'] = (
    (elasticity_pivot['avg_quantity_Campaign'] - elasticity_pivot['avg_quantity_Normal Day']) / elasticity_pivot['avg_quantity_Normal Day'] * 100
).round(2)

print(elasticity_pivot)

      category  avg_price_Campaign  avg_price_Normal Day  \
0       Beauty              551.74                637.67
1  Electronics            12463.83              13414.22
2      Fashion             1933.33               2272.73
3    Groceries              137.74                143.25
4         Home             6400.68               7257.39

   avg_discount_pct_Campaign  avg_discount_pct_Normal Day  \
0                      13.79                         0.55
1                      10.03                         0.40
2                      17.64                         1.18
3                       6.48                         0.47
4                      10.00                         0.44

   avg_quantity_Campaign  avg_quantity_Normal Day  demand_change_pct
0                   1.44                     1.41               2.13
1                   1.41                     1.41               0.00
2                   1.43                     1.40               2.14
3                   1.40                     1.40               0.00
4                   1.41                     1.41               0.00

In [69]:
elasticity_pivot.to_csv('price_elasticity.csv', index=False)
print("✅ Saved!")

✅ Saved!

ทำ 3: Delivery Bottleneck Analysis (เทศกาลขนส่งล่ม): คำนวณความต่างของเวลาจัดส่งจริงเทียบกับที่คาดการณ์ บีบออกมาเป็นจำนวนวัน เพื่อพิสูจน์สถิติดูว่า ออร์เดอร์ที่สั่งในช่วงแคมเปญใหญ่ๆ มีโอกาสส่งล่าช้า (Delay) กว่าวันธรรมดากี่เปอร์เซ็นต์

In [75]:
df_items.head()

,order_item_id,order_id,product_id,quantity,unit_price,unit_price_after_discount,line_total,discount_percent,commission_amount,maintenance_amount,shipping_fee_item,estimated_delivery_start,estimated_delivery_end,item_status,is_campaign,product_campaign_id
0,1,1,P002264,1,6823.94,6025.54,6025.54,11.7,482.04,0.00,200.0,2025-12-12,2025-12-14 00:00:00,Completed,1,
1,2,2,P003102,1,7955.43,7955.43,7955.43,0.0,636.43,0.00,150.0,2023-04-06,2023-04-08 00:00:00,Cancelled,0,
2,3,3,P002758,1,34.34,34.34,34.34,0.0,1.03,0.00,50.0,2024-09-21,2024-09-23 00:00:00,Completed,0,
3,4,4,P001537,1,14647.17,14647.17,14647.17,0.0,1171.77,0.00,150.0,2024-11-21,2024-11-22 00:00:00,Cancelled,0,
4,5,5,P004583,2,127.13,127.13,254.26,0.0,7.63,5.09,50.0,2025-06-09,2025-06-11 00:00:00,Completed,0,

In [83]:
# ── Task 3: Delivery Bottleneck Analysis ──

# Step 1: Convert to datetime
df_items['estimated_delivery_start'] = pd.to_datetime(df_items['estimated_delivery_start'])
df_items['estimated_delivery_end']   = pd.to_datetime(df_items['estimated_delivery_end'])
df_orders['order_date']              = pd.to_datetime(df_orders['order_date'])

# Step 2: Merge orders + items + campaigns
df_delivery = pd.merge(df_items, df_orders[['order_id', 'order_date', 'campaign_id']], on='order_id', how='left')
df_delivery = pd.merge(df_delivery, df_campaigns[['campaign_id', 'campaign_name']], on='campaign_id', how='left')
df_delivery['campaign_name'] = df_delivery['campaign_name'].fillna('Normal Day') # fillna is fill the NaN

# Step 3: Filter Completed only
df_delivery = df_delivery[df_delivery['item_status'] == 'Completed']

# Step 4: คำนวณจำนวนวัน
df_delivery['estimated_days'] = (df_delivery['estimated_delivery_end'] - df_delivery['order_date']).dt.days

# Step 5: สรุปต่อแคมเปญ
summary = df_delivery.groupby('campaign_name')['estimated_days'].mean().round(2).reset_index()
summary.columns = ['campaign_name', 'avg_delivery_days'] #create columns name
summary = summary.sort_values('avg_delivery_days', ascending=False) # this is max to min

print(summary)
summary.to_csv('delivery_summary.csv', index=False)

   campaign_name  avg_delivery_days
3       9.9 Sale               2.84
1     11.11 Sale               2.81
2     12.12 Sale               2.81
4     Normal Day               2.81
0     10.10 Sale               2.80
5  Songkran Sale               2.79

In [84]:
summary.to_csv('delivery_summary.csv', index=False)
print("✅ Saved!")

✅ Saved!

ทำ 4: Product ABC & Campaign Mapping: นำผลการจัดกลุ่มสินค้า 80/20 (Pareto) มาจับคู่ดูว่า สินค้าตัวท็อปที่เป็นฮีโร่แบกรายได้กลุ่ม A มันทำยอดขายได้จาก "ช่วงเวลาจัดแคมเปญ" หรือขายได้ด้วยตัวมันเองอยู่แล้วตลอดทั้งปี

In [94]:
# Step 1: Merge + Filter
df_abc = pd.merge(df_items, df_orders[['order_id', 'campaign_id']], on='order_id', how='left')
df_abc = pd.merge(df_abc, df_campaigns[['campaign_id','campaign_name']], on='campaign_id', how='left')
df_abc['campaign_name'] = df_abc['campaign_name'].fillna('Normal Day')
df_abc = df_abc[df_abc['item_status'] == 'Completed']

# Step 2: แบ่ง A/B/C ต่อ product
product_rev = df_abc.groupby('product_id')['line_total'].sum().sort_values(ascending=False).reset_index() # จัดกลุ่มและเรียงลำดับ
product_rev['cum_pct'] = product_rev['line_total'].cumsum() / product_rev['line_total'].sum() * 100 # คำนวณ % สะสม (Cumulative Percentage)


#บรรทัดนี้คือการ "แปะป้าย" ตามหลักกฎพาเรโต (80/20 Rule) ที่นิยมใช้กัน:
#•	กลุ่ม A (x <= 80): คือ "สินค้าขายดีระดับพระกาฬ" ที่ทำรายได้ให้บริษัทถึง 80% ของรายได้ทั้งหมด (แม้จะมีจำนวน SKU น้อยชิ้น)
#•	กลุ่ม B (80 < x <= 95): คือ "สินค้ากลุ่มรอง" ที่ช่วยทำรายได้เพิ่มขึ้นมาจนถึง 95%
#•	กลุ่ม C (ที่เหลือ): คือ "สินค้ากลุ่มท้ายตาราง" ที่สร้างรายได้ได้น้อยมากเมื่อเทียบกับกลุ่มอื่น ๆ
product_rev['abc_group'] = product_rev['cum_pct'].apply(lambda x :'A' if x <= 80 else ('B' if x <= 95 else 'C'))

# Step 3: Merge abc_group กลับ
df_abc = pd.merge(df_abc, product_rev[['product_id', 'abc_group']], on='product_id', how='left')
# create period for name campaign and normal day
df_abc['period'] = df_abc['campaign_name'].apply(lambda x : 'Normal Day' if x == 'Normal Day' else 'Campaign')

pd.set_option('display.float_format', '{:,.2f}'.format)

#
result = df_abc.groupby(['abc_group','period'])['line_total'].sum().reset_index() # group byA,B,C & campaign and sum(line total) and reset index
result.columns = ['abc_group','period','total_revenue']# set name column

result['revenue_pct'] = (
    result['total_revenue'] / result.groupby('abc_group')['total_revenue'].transform('sum') * 100
).round(2) # add new column name and cal to find revenue pct (percent)

result

  abc_group      period    total_revenue  revenue_pct
0         A    Campaign    74,226,332.69         3.04
1         A  Normal Day 2,368,519,292.60        96.96
2         B    Campaign    16,740,952.66         3.64
3         B  Normal Day   442,935,327.12        96.36
4         C    Campaign     5,562,116.07         3.64
5         C  Normal Day   147,317,043.73        96.36

In [93]:
result.to_csv('product_abc.csv', index=False)
print("✅ Saved!")

✅ Saved!

ทำ 5: Campaign ROI (Return on Investment) Estimation: เขียนสูตรคำนวณหาความคุ้มค่า โดยเอารายได้ช่วงแคมเปญ หักลบเปอร์เซ็นต์ส่วนลด หักลบค่า Commission และค่าบำรุงระบบหลังบ้าน เพื่อเฟ้นหาแคมเปญที่กำไรสุทธิ (Net Margin) ดีที่สุดจริงๆ

In [103]:
df_roi = pd.merge(df_items, df_orders[['order_id','campaign_id']], on='order_id',how='left')
df_roi = pd.merge(df_roi, df_campaigns[['campaign_id','campaign_name']], on='campaign_id', how='left')
df_roi['campaign_name'] = df_roi['campaign_name'].fillna('Normal Day')
df_roi = df_roi[df_roi['item_status'] == 'Completed']

roi_summary = df_roi.groupby('campaign_name').agg(
    total_revenue = ('line_total', 'sum'),
    total_discount = ('discount_percent', lambda x: (x * df_roi.loc[x.index,'line_total'] / 100).sum()),
    total_commission = ('commission_amount', 'sum'),
    total_maintenence = ('maintenance_amount','sum')
).round(2).reset_index()

roi_summary['net_profit'] = roi_summary['total_revenue'] - roi_summary['total_discount'] - roi_summary['total_commission'] - roi_summary['total_maintenence'].round(2)

roi_summary['roi_pct'] = (roi_summary['net_profit'] / roi_summary['total_revenue'] * 100).round(2)

roi_summary = roi_summary.sort_values('roi_pct', ascending=False)

print(roi_summary)

   campaign_name    total_revenue  total_discount  total_commission  \
4     Normal Day 2,958,771,663.45   11,797,308.36    208,042,852.01
2     12.12 Sale    30,778,434.83    3,139,625.06      2,172,918.44
1     11.11 Sale    24,684,596.85    2,508,999.72      1,761,068.49
5  Songkran Sale     9,880,029.31    1,011,554.29        702,117.51
0     10.10 Sale    15,800,134.88    1,630,599.89      1,119,815.70
3       9.9 Sale    15,386,205.55    1,588,772.22      1,094,161.89

   total_maintenence       net_profit  roi_pct
4       2,992,442.91 2,735,939,060.17    92.47
2          26,734.90    25,439,156.43    82.65
1          23,717.96    20,390,810.68    82.61
5          10,474.50     8,155,883.01    82.55
0          13,401.89    13,036,317.40    82.51
3          15,081.26    12,688,190.18    82.46

In [104]:
roi_summary.to_csv('campaign_roi.csv', index=False)
print("✅ Saved!")

✅ Saved!